TY-2366 build ios prod (#135)
Ticket:

- [TY-2366]


**Update:** lto error was addressed in #140 

---

can't use `lto` because of:
https://github.com/rust-lang/rust/issues/51009

running:
`RUSTFLAGS="-Ccodegen-units=1 -Clto=on -Cembed-bitcode=yes" just compile-ios-local`

gives the error:
```
error: lto can only be run for executables, cdylibs and static library outputs

error: could not compile `hyper` due to previous error
```

but `-Ccodegen-units=1` alone still decreases the size from 221mb to 144mb

[TY-2366]: https://xainag.atlassian.net/browse/TY-2366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ